site_name: WiseGuy AI Consulting
site_url: https://camronh.github.io/WiseGuy-Blog/

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Dark mode (now first, so it's the default)
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: cyan
    # Light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: light blue

plugins:
  - search
  - blog:
        blog_toc: true
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Blog Posts:
    - Blogs: blog/index.md
    - Experiments:
      - Overview: experiments/experiments_overview.md
      - Context Length Experiment: experiments/Context_Length_AppStoreV2.ipynb
  - Services: services.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/camronh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CamBrazy3
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/CamronHaider

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list