site_name: WiseGuy AI
site_url: https://camronh.github.io/WiseGuy-Blog/
site_description: AI Dev Blog
site_author: WiseGuy AI Team

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal 
      accent: deep purple
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal 
      accent: deep purple

plugins:
  - search
  - blog:
        blog_toc: true
  # - tags
  - mkdocs-jupyter
  - social

nav:
  - Home: index.md
  - Blog:
    - Blogs: blog/index.md
  - Experiments:
    - Overview: experiments/index.md
    - Context Length Experiment: experiments/Context_Length_AppStoreV2.ipynb
  # - Get In Touch: contact.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/camronh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CamBrazy3
  generator: true
  analytics:
    provider: google
    property: G-48MNVEHYNL

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list