site_name: WiseGuy AI Consulting
site_url: https://camronh.github.io/WiseGuy-Blog/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight    
    - navigation.indexes
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Dark mode (now first, so it's the default)
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: cyan
    # Light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: light blue

plugins:
  - search
  - blog
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Services: services.md
  - About: about.md
  - Blog:
    - Blog: blog/index.md
    - Experiments:
      - Overview: experiments/experiments_overview.md
      - Context Length Experiment: experiments/Context_Length_AppStoreV2.ipynb

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/YourGitHubUsername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/YourTwitterHandle
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/YourLinkedInProfile

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list